# Running settings
exp_script: "src.exp2"

# Define db root
#db_root:  "/media/alergn/hdd/datasets/audio/speech/TCD-VOIP/"
#mos_lqs_csv: "subjective_scores_cond.csv"
csv_speech: data/img_mos_metrics.csv

# METRICS
# Speech: 1) PESQ, 2) NISQA, 3) VISQOL
# Image: 1) SSIM, 2) ... TBD
metric: 'ssim'

# DATABASES
# Speech: 1) P23_EXP1, 2) P23_EXP3, 3) TCD-VOIP
# IMAGE: TBD
db: 'JPEGCoreExperiment'

# Define output directory
out_dir: ./experiments/exp2/

# *** PARAMETER SETTINGS ***
# Min and max number of raters
min: 8
max: 16
min_db: 1
max_db: 16

# Number of combinations
S: 1000

# Metrics you want to calculates
metric_names: ['pcc', 'srcc', 'ktau', 'cci']